"""
PDF Generation Service for KrishiAI
Generates professional PDF reports from chat conversations
"""

import io
import os
from datetime import datetime
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
import firebase_admin
from firebase_admin import credentials, firestore
import re

# Initialize Firebase Admin if not already initialized
if not firebase_admin._apps:
    # This will be initialized in app.py, but we check here for safety
    pass

def get_firestore_client():
    """Get Firestore client"""
    return firestore.client()

def fetch_chat_messages(user_id: str, chat_id: str) -> tuple:
    """
    Fetch chat messages from Firestore
    Returns: (chat_title, messages_list)
    """
    db = get_firestore_client()
    
    # Get chat metadata
    chat_ref = db.collection('users').document(user_id).collection('chats').document(chat_id)
    chat_doc = chat_ref.get()
    
    if not chat_doc.exists:
        raise ValueError(f"Chat {chat_id} not found")
    
    chat_data = chat_doc.to_dict()
    chat_title = chat_data.get('title', 'AI Advisory Report')
    
    # Get messages
    messages_ref = chat_ref.collection('messages')
    messages_query = messages_ref.order_by('createdAt').stream()
    
    messages = []
    for msg_doc in messages_query:
        msg_data = msg_doc.to_dict()
        messages.append({
            'role': msg_data.get('role', 'user'),
            'content': msg_data.get('content', ''),
            'timestamp': msg_data.get('createdAt')
        })
    
    return chat_title, messages

def format_markdown_to_pdf_content(text: str) -> List[str]:
    """
    Convert markdown text to PDF-friendly paragraphs
    Returns list of formatted text chunks with style indicators
    """
    lines = text.split('\n')
    formatted_content = []
    
    for line in lines:
        line = line.strip()
        if not line:
            formatted_content.append(('spacer', ''))
            continue
        
        # Headers
        if line.startswith('### '):
            formatted_content.append(('h3', line[4:]))
        elif line.startswith('## '):
            formatted_content.append(('h2', line[3:]))
        elif line.startswith('# '):
            formatted_content.append(('h1', line[2:]))
        # Bold text
        elif '**' in line:
            # Convert **text** to <b>text</b>
            formatted_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            formatted_content.append(('normal', formatted_line))
        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            formatted_content.append(('bullet', line[2:]))
        # Numbered lists
        elif re.match(r'^\d+\.\s', line):
            formatted_content.append(('numbered', line))
        else:
            formatted_content.append(('normal', line))
    
    return formatted_content

def create_pdf_header(canvas_obj, doc):
    """Create PDF header with KrishiAI branding"""
    canvas_obj.saveState()
    
    # Header background
    canvas_obj.setFillColor(colors.HexColor('#2D5F4F'))
    canvas_obj.rect(0, letter[1] - 1.2*inch, letter[0], 1.2*inch, fill=True, stroke=False)
    
    # Title
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont('Helvetica-Bold', 24)
    canvas_obj.drawString(0.75*inch, letter[1] - 0.7*inch, 'KrishiAI')
    
    canvas_obj.setFont('Helvetica', 14)
    canvas_obj.drawString(0.75*inch, letter[1] - 0.95*inch, 'AI Advisory Report')
    
    # Date
    canvas_obj.setFont('Helvetica', 10)
    date_str = datetime.now().strftime('%d %B %Y')
    canvas_obj.drawRightString(letter[0] - 0.75*inch, letter[1] - 0.85*inch, date_str)
    
    canvas_obj.restoreState()

def create_pdf_footer(canvas_obj, doc):
    """Create PDF footer"""
    canvas_obj.saveState()
    
    # Footer line
    canvas_obj.setStrokeColor(colors.HexColor('#E6E6E6'))
    canvas_obj.setLineWidth(0.5)
    canvas_obj.line(0.75*inch, 0.75*inch, letter[0] - 0.75*inch, 0.75*inch)
    
    # Footer text
    canvas_obj.setFillColor(colors.HexColor('#555555'))
    canvas_obj.setFont('Helvetica', 9)
    canvas_obj.drawString(0.75*inch, 0.5*inch, 'Generated by KrishiAI')
    
    # Page number
    page_num = canvas_obj.getPageNumber()
    canvas_obj.drawRightString(letter[0] - 0.75*inch, 0.5*inch, f'Page {page_num}')
    
    canvas_obj.restoreState()

def generate_chat_pdf(user_id: str, chat_id: str) -> io.BytesIO:
    """
    Generate PDF from chat conversation
    Returns: BytesIO buffer containing the PDF
    """
    # Fetch chat data
    chat_title, messages = fetch_chat_messages(user_id, chat_id)
    
    # Create PDF buffer
    buffer = io.BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=1.5*inch,
        bottomMargin=1*inch
    )
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#2D5F4F'),
        spaceAfter=12,
        alignment=TA_LEFT,
        fontName='Helvetica-Bold'
    )
    
    h1_style = ParagraphStyle(
        'CustomH1',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#2D5F4F'),
        spaceAfter=10,
        spaceBefore=14,
        fontName='Helvetica-Bold'
    )
    
    h2_style = ParagraphStyle(
        'CustomH2',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2D5F4F'),
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    h3_style = ParagraphStyle(
        'CustomH3',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=colors.HexColor('#2D5F4F'),
        spaceAfter=6,
        spaceBefore=10,
        fontName='Helvetica-Bold'
    )
    
    user_style = ParagraphStyle(
        'UserMessage',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#1E1E1E'),
        spaceAfter=6,
        leftIndent=0,
        fontName='Helvetica-Bold'
    )
    
    assistant_style = ParagraphStyle(
        'AssistantMessage',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#1E1E1E'),
        spaceAfter=4,
        leftIndent=0,
        alignment=TA_LEFT
    )
    
    bullet_style = ParagraphStyle(
        'BulletPoint',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#1E1E1E'),
        leftIndent=20,
        bulletIndent=10,
        spaceAfter=4
    )
    
    # Build PDF content
    story = []
    
    # Chat title
    story.append(Paragraph(chat_title, title_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Messages
    for idx, msg in enumerate(messages):
        role = msg['role']
        content = msg['content']
        
        if role == 'user':
            # User message header
            story.append(Paragraph(f'<b>Question:</b>', user_style))
            story.append(Spacer(1, 0.1*inch))
            
            # User message content
            story.append(Paragraph(content, assistant_style))
            story.append(Spacer(1, 0.2*inch))
            
        elif role in ['assistant', 'model']:
            # Assistant message header
            story.append(Paragraph(f'<b>AI Response:</b>', user_style))
            story.append(Spacer(1, 0.1*inch))
            
            # Format and add assistant content
            formatted_content = format_markdown_to_pdf_content(content)
            
            for content_type, text in formatted_content:
                if content_type == 'spacer':
                    story.append(Spacer(1, 0.1*inch))
                elif content_type == 'h1':
                    story.append(Paragraph(text, h1_style))
                elif content_type == 'h2':
                    story.append(Paragraph(text, h2_style))
                elif content_type == 'h3':
                    story.append(Paragraph(text, h3_style))
                elif content_type == 'bullet':
                    story.append(Paragraph(f'• {text}', bullet_style))
                elif content_type == 'numbered':
                    story.append(Paragraph(text, bullet_style))
                else:  # normal
                    story.append(Paragraph(text, assistant_style))
            
            story.append(Spacer(1, 0.3*inch))
            
            # Add separator between conversations
            if idx < len(messages) - 1:
                story.append(Spacer(1, 0.1*inch))
    
    # Build PDF with header and footer
    doc.build(story, onFirstPage=create_pdf_header, onLaterPages=create_pdf_header,
              canvasmaker=lambda *args, **kwargs: canvas.Canvas(*args, **kwargs))
    
    # Add footers
    buffer.seek(0)
    
    return buffer
